### ISSUE TITLE
Kafka Manager error Failed to parse endpoint OUTSIDE

### ISSUE THREAD

**Issue by solsson** [Yolean/kubernetes-kafka#142]
Logs for #83 and 77cdb36 show:

```
[error] k.m.m.ActorModel$BrokerIdentity$ - Failed to parse endpoint : OUTSIDE://10.132.0.11:32400
java.util.NoSuchElementException: key not found: OUTSIDE
	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.AbstractMap.default(Map.scala:59) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.AbstractMap.apply(Map.scala:59) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at kafka.manager.model.SecurityProtocol$.apply(model.scala:415) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
	at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7$$anonfun$apply$7.apply(ActorModel.scala:262) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
	at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7$$anonfun$apply$7.apply(ActorModel.scala:259) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
	at scalaz.Validation$.fromTryCatchNonFatal(Validation.scala:397) ~[org.scalaz.scalaz-core_2.11-7.2.4.jar:na]
	at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7.apply(ActorModel.scala:259) [kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
	at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7.apply(ActorModel.scala:258) [kafka-manager.kafka-manager-1.3.3.14-sans-exte
```

... as described and currently unresolved in https://github.com/yahoo/kafka-manager/issues/455 https://github.com/yahoo/kafka-manager/issues/433 https://github.com/yahoo/kafka-manager/issues/421.

I don't think this has any impact on practical Kafka Manager use.

**Comment by cemo** [comment]
https://github.com/yahoo/kafka-manager/pull/484 seems resolving this. Any chance to upgrade and release a docker image please?

**Comment by solsson** [comment]
The [image](https://github.com/solsson/dockerfiles/blob/master/manager/Dockerfile) is built from tagged source so I'd like to wait for next release.

**Comment by cemo** [comment]
I had built image with new one but had some issues. I sticked with your image made a minor trick to suppress logs. 

https://gist.github.com/cemo/6e7f4607d3b9abe66ffe08ee9c428761

**Comment by solsson** [comment]
23736e2 should include https://github.com/yahoo/kafka-manager/pull/484. I don't see the above error.
