### ISSUE TITLE
Failed to resolve address: pzoo-2.pzoo

### ISSUE THREAD

**Issue by mikep-locol-media** [Yolean/kubernetes-kafka#176]
I may have the same problem as #28 

This is what I am getting. One thing I am not clear.. I have both the pzoo and the zoo services created. When I create 50pzoo.yml, I get errors trying to reach zoo-x.zoo, when I create 51zoo.yml, I get errors trying to reach pzoo-x.pzoo. Does that make sense?

Doing this with Docker for Mac Kubernetes support.

```
[2018-05-01 04:34:02,143] INFO Reading configuration from: /etc/kafka/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2018-05-01 04:34:02,172] WARN Failed to resolve address: pzoo-2.pzoo (org.apache.zookeeper.server.quorum.QuorumPeer)
java.net.UnknownHostException: pzoo-2.pzoo: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:166)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.&lt;init&gt;(QuorumPeer.java:151)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:238)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:150)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
[2018-05-01 04:34:02,190] WARN Failed to resolve address: pzoo-1.pzoo (org.apache.zookeeper.server.quorum.QuorumPeer)
java.net.UnknownHostException: pzoo-1.pzoo: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:166)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.&lt;init&gt;(QuorumPeer.java:151)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:238)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:150)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
[2018-05-01 04:34:02,195] WARN Failed to resolve address: pzoo-0.pzoo (org.apache.zookeeper.server.quorum.QuorumPeer)

```

**Comment by mikep-locol-media** [comment]
Yup... Kafka came up nice and clean.. Good work guys. Thanks much. This is nice. Up and running, less than two hours from "start reading the repo" to Kafka up.
