### ISSUE TITLE
Kafka-security 

### ISSUE THREAD

**Issue by ankitraijr** [Yolean/kubernetes-kafka#180]
Hi,
I have deployed Kafka with three nodes in kubernetes and it is working all good but now I want to implement SSL security. I have created all key-store and trust-store necessary for implementing SSL authentication between Kafka broker and client and I tried to configure my certificates through config-map with a particular directory but it gives me the following error. 
java.io.IOException: Invalid keystore format

Is there any another way to pass those certificates inside Kafka pods like secrets ....
Please help me if anyone has any idea.
Thanks.

**Comment by solsson** [comment]
I haven't tried this with Kafka, but a few years ago with Keycloak that is also java. I seem to recall that jks tooling and format came with a bit of a learning curve. Care to describe how you produced the configmap? I've never tried configmap with binary files.

**Comment by ankitraijr** [comment]
@solsson  Thanks for the help. And I was using k8s config-map instead of k8s secret. It worked with passing certificates as a secret.

**Comment by ankitraijr** [comment]
Hi,
I have enabled SSL security by updating the broker-configmap and also init.sh for exposing SSL port for the outside of kubernetes cluster.

also, I have updated the kafka.yml file by adding few extra ports and few extra mounting points with a secret. Also, I have created service for SSL protocol ex:- outside-SSL-0.

Now I am able to produce message but unable to consume the message.

Below are the following changes I made to the respective files.

**init.sh:-**
`       OUTSIDE_PORT=3240${KAFKA_BROKER_ID}
        OUTSIDE_SSL_PORT=3230${KAFKA_BROKER_ID}
        #SEDS+=("s|#init#advertised.listeners=OUTSIDE://#init#|advertised.listeners=OUTSIDE://${OUTSIDE_HOST}:${OUTSIDE_PORT}|")
        SEDS+=("s|#init#advertised.listeners=OUTSIDE://#init#|advertised.listeners=OUTSIDE://${OUTSIDE_HOST}:${OUTSIDE_PORT},OUTSIDE_SSL://${OUTSIDE_HOST}:${OUTSIDE_SSL_PORT}|")`



**server.properties**

`    #listeners=OUTSIDE://:9094,PLAINTEXT://:9092
    listeners=OUTSIDE://:9094,PLAINTEXT://:9092,SSL://:9093,OUTSIDE_SSL://:9097




    security.inter.broker.protocol=SSL
    ssl.client.auth=required
    ssl.truststore.location=/tmp/kafka.server.truststore.jks
    ssl.truststore.password=*********
    ssl.keystore.location=/tmp/kafka.server.keystore.jks
    ssl.keystore.password=*********
    ssl.key.password=*********


    # Hostname and port the broker will advertise to producers and consumers. If not set,
    # it uses the value for "listeners" if configured.  Otherwise, it will use the value
    # returned from java.net.InetAddress.getCanonicalHostName().
    #advertised.listeners=PLAINTEXT://your.host.name:9092
    ##init#advertised.listeners=OUTSIDE://#init#,PLAINTEXT://:9092
    #init#advertised.listeners=OUTSIDE://#init#,PLAINTEXT://:9092,SSL://:9093
    # Maps listener names to security protocols, the default is for them to be the same. See the config documentation for more details
    #listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
    #listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,OUTSIDE:PLAINTEXT
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,OUTSIDE:PLAINTEXT,OUTSIDE_SSL:SSL

    #inter.broker.listener.name=PLAINTEXT`


**50kafka.yml**
`        ports:
        - name: ssl-outside
          containerPort: 9097
        - name: ssl-inside
          containerPort: 9093
        - name: inside
          containerPort: 9092
        - name: outside
          containerPort: 9094
        - name: jmx
          containerPort: 5555
        - name: prometheus
          containerPort: 7071
        command:
        - ./bin/kafka-server-start.sh
        - /etc/kafka/server.properties
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: 9092
          timeoutSeconds: 1
        volumeMounts:
        - name: ssl-config
          mountPath: /tmp
        - name: config
          mountPath: /etc/kafka
        - name: data
          mountPath: /var/lib/kafka/data
      volumes:
      - name: configmap
        configMap:
          name: broker-config
      - name: ssl-config
        secret:
          secretName: kafka-ssl-security
      - name: config
        emptyDir: {}
      - name: data
        emptyDir: {}`

**Comment by ankitraijr** [comment]
Hi,
I have implemented Kafka-SSL security inside my pod there no error during startup and also I  can produce/consume message from inside/outside K8s cluster successfully also I mam able to telnet on both plaintext and SSL port within the containers. But when I am trying  to connect to Kafka on SSL port is giving me the following error.
Also, I have verified the key(Keystore/Truststore) are fine and its working properly with the Kafka running on Server (outside K8s).



	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:389)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:469)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:328)
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:255)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:79)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:474)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:412)
	... 3 more
Caused by: java.security.InvalidKeyException: The security strength of SHA-1 digest algorithm is not sufficient for this key size
	at sun.security.provider.DSA.checkKey(DSA.java:111)
	at sun.security.provider.DSA.engineInitSign(DSA.java:143)
	at java.security.SignatureSpi.engineInitSign(SignatureSpi.java:103)
	at java.security.Signature$Delegate.init(Signature.java:1155)
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1112)
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1185)
	at java.security.Signature.initSign(Signature.java:550)
	at sun.security.ssl.HandshakeMessage$DH_ServerKeyExchange.<init>(HandshakeMessage.java:750)
	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:882)
	... 16 more

**Comment by solsson** [comment]
The error message looks pretty clear. Could it be due to how your key was generated?

**Comment by abdeokar23** [comment]
@ankitraijr I'm trying to get the same thing done, could you please list the steps you took to get the broker running with the required security config? Is it similar to setting the required fields in x.properties files as we would do on a kafka broker not specifically inside a kubernetes pod?
