### ISSUE TITLE
Kafka fails to establish connection if server.properties has zookeeper.connect=zookeeper:2181

### ISSUE THREAD

**Issue by csarora** [Yolean/kubernetes-kafka#20]
I have setup kafka & zookeeper , zookeeper came up fine and is running but kafka pods fail if  **_config/server.properties has zookeeper.connect=zookeeper-svc:2181_**

IF i replace zookeerper:2181 with ip address of zookeeper pods then connection succeeds 
**_config/server.properties has zookeeper.connect=10.0.40.0:2181,10.0.0.32:2181_**

**Problem :  
I want to use podname:2181 or servicename:2181 in zookeeper.connect field.
Right now using zoo-pod-ip:port is hard coding on reboot the IP will be lost , can you please help in getting the issue resolved.
**

```
Error :
[2017-02-16 05:04:57,615] INFO Initiating client connection, connectString=zookeeper-svc:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@68999068 (org.apache.zookeeper.ZooKeeper)
[2017-02-16 05:04:57,627] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2017-02-16 05:05:06,628] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-02-16 05:05:07,641] INFO **Opening socket connection to server zookeeper-svc.default.svc.cluster.local/10.98.86.77:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)**
[2017-02-16 05:05:07,685] INFO Socket connection established to zookeeper-svc.default.svc.cluster.local/10.98.86.77:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2017-02-16 05:05:07,743] INFO Session establishment complete on server zookeeper.default.svc.cluster.local/10.98.86.77:2181, sessionid = 0x25a454d326e0000, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2017-02-16 05:05:07,747] INFO **Session: 0x25a454d326e0000 closed** (org.apache.zookeeper.ZooKeeper)
[2017-02-16 05:05:07,748] INFO EventThread shut down for session: 0x25a454d326e0000 (org.apache.zookeeper.ClientCnxn)
[2017-02-16 05:05:07,748] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkTimeoutException: **Unable to connect to zookeeper server within timeou**t: 9000
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
        at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:76)
        at kafka.utils.ZkUtils$.apply(ZkUtils.scala:58)
        at kafka.server.KafkaServer.initZk(KafkaServer.scala:327)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:200)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
        at kafka.Kafka$.main(Kafka.scala:67)
        at kafka.Kafka.main(Kafka.scala)
[2017-02-16 05:05:07,750] INFO shutting down (kafka.server.KafkaServer)
[2017-02-16 05:05:07,753] INFO shut down completed (kafka.server.KafkaServer)
[2017-02-16 05:05:07,754] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 9000
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
        at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:76)
        at kafka.utils.ZkUtils$.apply(ZkUtils.scala:58)
        at kafka.server.KafkaServer.initZk(KafkaServer.scala:327)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:200)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
        at kafka.Kafka$.main(Kafka.scala:67)
        at kafka.Kafka.main(Kafka.scala)
[2017-02-16 05:05:07,755] INFO shutting down (kafka.server.KafkaServer)
```

**Comment by solsson** [comment]
Have you verified that you have both services in the same namespace? Maybe you're running yaml from before https://github.com/Yolean/kubernetes-kafka/pull/18?

```bash
$ kubectl -n kafka get service
NAME        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
broker      None           <none>        9092/TCP            1d
kafka       10.7.240.217   <none>        9092/TCP            1d
zoo         None           <none>        2888/TCP,3888/TCP   1d
zookeeper   10.7.255.129   <none>        2181/TCP            1d
```

**Comment by csarora** [comment]
Yes everything is in same namespace, I am using everything in default namespace & the names of services are also different stateful set is "zookeeper" not zoo and service is zookeeper-svc, kafka stateful set is "kafka" not broker. If you look at error it resolves to IP from name but it does not connect.
& If i just replace dns name of zookeeper-svc to pords IP kafka pods come up fine and run successfully

root@ip-10-43-0-20:/home/ubuntu/templates/yolen/kubernetes-kafka# **kubectl get svc**
NAME             CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
kafka            None          <none>        9092/TCP            1m
kafka-svc        10.99.7.229   <none>        9092/TCP            1m
kubernetes       10.96.0.1     <none>        443/TCP             7d
zookeeper        None          <none>        2888/TCP,3888/TCP   6h
zookeeper-svc    10.98.86.77   <none>        2181/TCP            6h
root@ip-10-43-0-20:/home/ubuntu/templates/yolen/kubernetes-kafka# **kubectl  get po**
NAME                   READY     STATUS    RESTARTS   AGE
kafka-0                0/1       Error     2          56s
kafka-1                0/1       Error     2          55s
kafka-2                0/1       Error     2          54s
zookeeper-0            1/1       Running   0          6h
zookeeper-1            1/1       Running   0          6h
zookeeper-2            1/1       Running   0          6h
root@ip-10-43-0-20:/home/ubuntu/templates/yolen/kubernetes-kafka# **kubectl logs kafka-0|grep error**
[2017-02-16 11:44:25,181] INFO Opening socket connection to server **zookeeper-svc.default.svc.cluster.local/10.98.86.77:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2017-02-16 11:44:25,235] FATAL Fatal err**or during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
[2017-02-16 11:44:25,240] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)

**Comment by solsson** [comment]
I suggest we close this issue as the configuration differs significantly from what you get through the yaml's in this repository. I think your question should be asked in a Kafka or Zookeeper forum. Please re-open if you find that this is actually an issue with the kubernetes-kafka cluster setup.

**Comment by gemfield** [comment]
From my observation, when the cluster host environment has no internet access, the dns will cost much more time. So, change zookeeper.connection.timeout.ms from 6000 to 60000 may solve your issue.
