### ISSUE TITLE
Error while starting kafka

### ISSUE THREAD

**Issue by GauravAsthana1** [Yolean/kubernetes-kafka#256]
Kafka in windows not starting, giving the below error, however Zookeeper started fine. 

$ kafka-server-start.bat config\server.properties
[2019-03-31 12:30:45,160] INFO Registered kafka:type=kafka.Log4jController MBean                                                                                                                 (kafka.utils.Log4jControllerRegistration$)
[2019-03-31 12:30:45,191] ERROR Exiting Kafka due to fatal exception (kafka.Kafk                                                                                                                a$)
java.nio.file.NoSuchFileException: configserver.properties
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
        at java.nio.file.Files.newInputStream(Unknown Source)
        at org.apache.kafka.common.utils.Utils.loadProps(Utils.java:564)
        at kafka.Kafka$.getPropsFromArgs(Kafka.scala:42)
        at kafka.Kafka$.main(Kafka.scala:58)
        at kafka.Kafka.main(Kafka.scala)

Please suggest. 

Thanks 
Gaurav

**Comment by solsson** [comment]
This has nothing to do with kubernetes-kafka, I suppose?

**Comment by Volcantis** [comment]
Facing the same issue!

$ kubectl -n kafka logs kafka-0 -c init-config

+ KAFKA_BROKER_ID=0
+ sed -i s/#init#broker.id=#init#/broker.id=0/ /etc/kafka/server.properties
sed: can't read /etc/kafka/server.properties: No such file or directory
+ hash kubectl
++ kubectl get node gke-stage3-production-app-pool-ebbabb8e-5gmh '-o=go-template={{index .metadata.labels "failure-domain.beta.kubernetes.io/zone"}}'
+ ZONE=asia-east1-a
+ '[' 0 -ne 0 ']'
+ '[' xasia-east1-a == 'x<no value>' ']'
+ sed -i s/#init#broker.rack=#init#/broker.rack=asia-east1-a/ /etc/kafka/server.properties
sed: can't read /etc/kafka/server.properties: No such file or directory
+ kubectl -n kafka label pod kafka-0 kafka-broker-id=0
error: 'kafka-broker-id' already has a value (0), and --overwrite is false
++ kubectl get node gke-stage3-production-app-pool-ebbabb8e-5gmh -o 'jsonpath={.status.addresses[?(@.type=="InternalIP")].address}'
+ OUTSIDE_HOST=10.240.0.35
+ '[' 0 -ne 0 ']'
+ OUTSIDE_HOST=10.240.0.35:32400
+ sed -i 's|#init#advertised.listeners=OUTSIDE://#init#|advertised.listeners=OUTSIDE://10.240.0.35:32400|' /etc/kafka/server.properties
sed: can't read /etc/kafka/server.properties: No such file or directory

**Comment by Volcantis** [comment]
This occurred on upgrading kubernetes from 1.7 to 1.12

**Comment by Volcantis** [comment]
Solved this by copying the new broker-config mapping!

**Comment by kpraveersingh** [comment]
@Volcantis , where did you copy the new broker-config mapping from?
