### ISSUE TITLE
Lots of zoo and kafka pod reboots

### ISSUE THREAD

**Issue by ammills01** [Yolean/kubernetes-kafka#261]
Hey all,

I have a new kubernetes-kafka deployment in AKS.  I've left nearly every setting the same from the most recent version, did deploy RBAC, and deployed the entire solution to the default namespace of kafka.  The only settings I changed were for zookeeper, drives went to 10G and these changes were made:

initLimit=10
syncLimit=5
snap_retain_count=3
purge_interval=12
max_session_timeout=40000
min_session_timeout=4000

I have a node.js API setup to publish events to kafka and have proven that works well.  Last night, I established a durability test to send a small number of records through every second for 12 hours.  This morning I see all of my pods have rebooted numerous times throughout the night.  I've struggled with these reboots even when not load testing, which is why I changed the initLimit and syncLimit, but I'm at a loss now.  I've included some log files below but I don't find them super helpful and I'm not sure where else to look.

Any help trying to track this down is greatly appreciated.

![kafka-cluster](https://user-images.githubusercontent.com/9723534/55959803-1eb76880-5c31-11e9-9d04-89672f7e8e2a.png)

--previous logs from pzoo-2 zookeeper

`2019-04-11T10:37:59.885555133Z [2019-04-11 10:37:59,885] INFO Server environment:java.version=11.0.2 (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885573433Z [2019-04-11 10:37:59,885] INFO Server environment:java.vendor=Oracle Corporation (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885577533Z [2019-04-11 10:37:59,885] INFO Server environment:java.home=/usr/lib/jvm/jdk-11 (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.88578633Z [2019-04-11 10:37:59,885] INFO Server environment:java.class.path=/opt/kafka/bin/../libs/activation-1.1.1.jar:/opt/kafka/bin/../libs/aopalliance-repackaged-2.5.0-b42.jar:/opt/kafka/bin/../libs/argparse4j-0.7.0.jar:/opt/kafka/bin/../libs/audience-annotations-0.5.0.jar:/opt/kafka/bin/../libs/commons-lang3-3.8.1.jar:/opt/kafka/bin/../libs/connect-api-2.1.1.jar:/opt/kafka/bin/../libs/connect-basic-auth-extension-2.1.1.jar:/opt/kafka/bin/../libs/connect-file-2.1.1.jar:/opt/kafka/bin/../libs/connect-json-2.1.1.jar:/opt/kafka/bin/../libs/connect-runtime-2.1.1.jar:/opt/kafka/bin/../libs/connect-transforms-2.1.1.jar:/opt/kafka/bin/../libs/guava-20.0.jar:/opt/kafka/bin/../libs/hk2-api-2.5.0-b42.jar:/opt/kafka/bin/../libs/hk2-locator-2.5.0-b42.jar:/opt/kafka/bin/../libs/hk2-utils-2.5.0-b42.jar:/opt/kafka/bin/../libs/jackson-annotations-2.9.8.jar:/opt/kafka/bin/../libs/jackson-core-2.9.8.jar:/opt/kafka/bin/../libs/jackson-databind-2.9.8.jar:/opt/kafka/bin/../libs/jackson-jaxrs-base-2.9.8.jar:/opt/kafka/bin/../libs/jackson-jaxrs-json-provider-2.9.8.jar:/opt/kafka/bin/../libs/jackson-module-jaxb-annotations-2.9.8.jar:/opt/kafka/bin/../libs/javassist-3.22.0-CR2.jar:/opt/kafka/bin/../libs/javax.annotation-api-1.2.jar:/opt/kafka/bin/../libs/javax.inject-1.jar:/opt/kafka/bin/../libs/javax.inject-2.5.0-b42.jar:/opt/kafka/bin/../libs/javax.servlet-api-3.1.0.jar:/opt/kafka/bin/../libs/javax.ws.rs-api-2.1.1.jar:/opt/kafka/bin/../libs/javax.ws.rs-api-2.1.jar:/opt/kafka/bin/../libs/jaxb-api-2.3.0.jar:/opt/kafka/bin/../libs/jersey-client-2.27.jar:/opt/kafka/bin/../libs/jersey-common-2.27.jar:/opt/kafka/bin/../libs/jersey-container-servlet-2.27.jar:/opt/kafka/bin/../libs/jersey-container-servlet-core-2.27.jar:/opt/kafka/bin/../libs/jersey-hk2-2.27.jar:/opt/kafka/bin/../libs/jersey-media-jaxb-2.27.jar:/opt/kafka/bin/../libs/jersey-server-2.27.jar:/opt/kafka/bin/../libs/jetty-client-9.4.12.v20180830.jar:/opt/kafka/bin/../libs/jetty-continuation-9.4.12.v20180830.jar:/opt/kafka/bin/../libs/jetty-http-9.4.12.v20180830.jar:/opt/kafka/bin/../libs/jetty-io-9.4.12.v20180830.jar:/opt/kafka/bin/../libs/jetty-security-9.4.12.v20180830.jar:/opt/kafka/bin/../libs/jetty-server-9.4.12.v20180830.jar:/opt/kafka/bin/../libs/jetty-servlet-9.4.12.v20180830.jar:/opt/kafka/bin/../libs/jetty-servlets-9.4.12.v20180830.jar:/opt/kafka/bin/../libs/jetty-util-9.4.12.v20180830.jar:/opt/kafka/bin/../libs/jopt-simple-5.0.4.jar:/opt/kafka/bin/../libs/kafka-clients-2.1.1.jar:/opt/kafka/bin/../libs/kafka-log4j-appender-2.1.1.jar:/opt/kafka/bin/../libs/kafka-streams-2.1.1.jar:/opt/kafka/bin/../libs/kafka-streams-examples-2.1.1.jar:/opt/kafka/bin/../libs/kafka-streams-scala_2.12-2.1.1.jar:/opt/kafka/bin/../libs/kafka-streams-test-utils-2.1.1.jar:/opt/kafka/bin/../libs/kafka-tools-2.1.1.jar:/opt/kafka/bin/../libs/kafka_2.12-2.1.1-sources.jar:/opt/kafka/bin/../libs/kafka_2.12-2.1.1.jar:/opt/kafka/bin/../libs/log4j-1.2.17.jar:/opt/kafka/bin/../libs/lz4-java-1.5.0.jar:/opt/kafka/bin/../libs/maven-artifact-3.6.0.jar:/opt/kafka/bin/../libs/metrics-core-2.2.0.jar:/opt/kafka/bin/../libs/osgi-resource-locator-1.0.1.jar:/opt/kafka/bin/../libs/plexus-utils-3.1.0.jar:/opt/kafka/bin/../libs/reflections-0.9.11.jar:/opt/kafka/bin/../libs/rocksdbjni-5.14.2.jar:/opt/kafka/bin/../libs/scala-library-2.12.7.jar:/opt/kafka/bin/../libs/scala-logging_2.12-3.9.0.jar:/opt/kafka/bin/../libs/scala-reflect-2.12.7.jar:/opt/kafka/bin/../libs/slf4j-api-1.7.25.jar:/opt/kafka/bin/../libs/slf4j-log4j12-1.7.25.jar:/opt/kafka/bin/../libs/snappy-java-1.1.7.2.jar:/opt/kafka/bin/../libs/validation-api-1.1.0.Final.jar:/opt/kafka/bin/../libs/zkclient-0.11.jar:/opt/kafka/bin/../libs/zookeeper-3.4.13.jar:/opt/kafka/bin/../libs/zstd-jni-1.3.7-1.jar (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885867729Z [2019-04-11 10:37:59,885] INFO Server environment:java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885872829Z [2019-04-11 10:37:59,885] INFO Server environment:java.io.tmpdir=/tmp (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885876829Z [2019-04-11 10:37:59,885] INFO Server environment:java.compiler=<NA> (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885880329Z [2019-04-11 10:37:59,885] INFO Server environment:os.name=Linux (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885920428Z [2019-04-11 10:37:59,885] INFO Server environment:os.arch=amd64 (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885939128Z [2019-04-11 10:37:59,885] INFO Server environment:os.version=4.15.0-1040-azure (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885947928Z [2019-04-11 10:37:59,885] INFO Server environment:user.name=root (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885951128Z [2019-04-11 10:37:59,885] INFO Server environment:user.home=/root (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.885954128Z [2019-04-11 10:37:59,885] INFO Server environment:user.dir=/opt/kafka (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.88736881Z [2019-04-11 10:37:59,887] INFO Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /var/lib/zookeeper/log/version-2 snapdir /var/lib/zookeeper/data/version-2 (org.apache.zookeeper.server.ZooKeeperServer)
2019-04-11T10:37:59.888061802Z [2019-04-11 10:37:59,887] INFO FOLLOWING - LEADER ELECTION TOOK - 95 (org.apache.zookeeper.server.quorum.Learner)
2019-04-11T10:37:59.892733643Z [2019-04-11 10:37:59,889] INFO Resolved hostname: zoo-1.zoo to address: zoo-1.zoo/10.179.236.152 (org.apache.zookeeper.server.quorum.QuorumPeer)
2019-04-11T10:37:59.895100413Z [2019-04-11 10:37:59,894] INFO Getting a diff from the leader 0xd0000009c (org.apache.zookeeper.server.quorum.Learner)
2019-04-11T10:38:00.363739417Z [2019-04-11 10:38:00,363] INFO The list of known four letter word commands is : [{1936881266=srvr, 1937006964=stat, 2003003491=wchc, 1685417328=dump, 1668445044=crst, 1936880500=srst, 1701738089=envi, 1668247142=conf, 2003003507=wchs, 2003003504=wchp, 1668247155=cons, 1835955314=mntr, 1769173615=isro, 1920298859=ruok, 1735683435=gtmk, 1937010027=stmk}] (org.apache.zookeeper.server.ServerCnxn)
2019-04-11T10:38:00.363773917Z [2019-04-11 10:38:00,363] INFO The list of enabled four letter word commands is : [[wchs, stat, stmk, conf, ruok, mntr, srvr, envi, srst, isro, dump, gtmk, crst, cons]] (org.apache.zookeeper.server.ServerCnxn)
2019-04-11T11:02:54.87416595Z [2019-04-11 11:02:54,872] WARN Connection broken for id 1, my id = 3, error =  (org.apache.zookeeper.server.quorum.QuorumCnxManager)
2019-04-11T11:02:54.87418425Z java.io.EOFException
2019-04-11T11:02:54.87418805Z 	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
2019-04-11T11:02:54.87419175Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$RecvWorker.run(QuorumCnxManager.java:1010)
2019-04-11T11:02:54.87419505Z [2019-04-11 11:02:54,874] WARN Interrupting SendWorker (org.apache.zookeeper.server.quorum.QuorumCnxManager)
2019-04-11T11:02:54.875268536Z [2019-04-11 11:02:54,874] WARN Interrupted while waiting for message on queue (org.apache.zookeeper.server.quorum.QuorumCnxManager)
2019-04-11T11:02:54.875297136Z java.lang.InterruptedException
2019-04-11T11:02:54.875300636Z 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
2019-04-11T11:02:54.875304336Z 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
2019-04-11T11:02:54.875321635Z 	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
2019-04-11T11:02:54.875325935Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.pollSendQueue(QuorumCnxManager.java:1094)
2019-04-11T11:02:54.875339635Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.access$700(QuorumCnxManager.java:74)
2019-04-11T11:02:54.875343235Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$SendWorker.run(QuorumCnxManager.java:929)
2019-04-11T11:02:54.875346135Z [2019-04-11 11:02:54,875] WARN Send worker leaving thread (org.apache.zookeeper.server.quorum.QuorumCnxManager)
2019-04-11T11:02:59.895091444Z [2019-04-11 11:02:59,894] INFO Received connection request /10.179.236.82:39924 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
2019-04-11T11:02:59.911507638Z [2019-04-11 11:02:59,911] INFO Notification: 1 (message format version), 1 (n.leader), 0xd0000009c (n.zxid), 0x1 (n.round), LOOKING (n.state), 1 (n.sid), 0xd (n.peerEpoch) FOLLOWING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
2019-04-11T11:02:59.911781335Z [2019-04-11 11:02:59,911] INFO Notification: 1 (message format version), 3 (n.leader), 0xd0000009c (n.zxid), 0xe (n.round), LOOKING (n.state), 1 (n.sid), 0xd (n.peerEpoch) FOLLOWING (my state) (org.apache.zookeeper.server.quorum.FastLeaderElection)
2019-04-11T11:08:35.667887916Z [2019-04-11 11:08:35,667] WARN Got zxid 0xd0000009d expected 0x1 (org.apache.zookeeper.server.quorum.Learner)
2019-04-11T11:08:35.668128013Z [2019-04-11 11:08:35,667] INFO Creating new log file: log.d0000009d (org.apache.zookeeper.server.persistence.FileTxnLog)`

--previous logs from kafka-2 broker

`2019-04-11T12:32:24.676797004Z [2019-04-11 12:32:24,676] INFO [Log partition=__consumer_offsets-12, dir=/var/lib/kafka/data/topics] Truncating to 0 has no effect as the largest offset in the log is -1 (kafka.log.Log)
2019-04-11T12:32:24.676800004Z [2019-04-11 12:32:24,676] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Truncating partition __consumer_offsets-9 to local high watermark 0 (kafka.server.ReplicaFetcherThread)
2019-04-11T12:32:24.676838804Z [2019-04-11 12:32:24,676] INFO [Log partition=__consumer_offsets-9, dir=/var/lib/kafka/data/topics] Truncating to 0 has no effect as the largest offset in the log is -1 (kafka.log.Log)
2019-04-11T12:32:24.676866003Z [2019-04-11 12:32:24,676] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Truncating partition __consumer_offsets-42 to local high watermark 0 (kafka.server.ReplicaFetcherThread)
2019-04-11T12:32:24.676869303Z [2019-04-11 12:32:24,676] INFO [Log partition=__consumer_offsets-42, dir=/var/lib/kafka/data/topics] Truncating to 0 has no effect as the largest offset in the log is -1 (kafka.log.Log)
2019-04-11T12:32:24.676945702Z [2019-04-11 12:32:24,676] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Truncating partition __consumer_offsets-24 to local high watermark 0 (kafka.server.ReplicaFetcherThread)
2019-04-11T12:32:24.676953002Z [2019-04-11 12:32:24,676] INFO [Log partition=__consumer_offsets-24, dir=/var/lib/kafka/data/topics] Truncating to 0 has no effect as the largest offset in the log is -1 (kafka.log.Log)
2019-04-11T12:32:24.677424296Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-0 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.677585594Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-3 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.677708393Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-0. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.677825991Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-6 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678343185Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-3. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678362985Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-9 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678367385Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-6. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678370685Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-12 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678373884Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-9. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678377084Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-15 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678380184Z [2019-04-11 12:32:24,677] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-12. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678383284Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-18 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678386484Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-15. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678389484Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-21 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678393184Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-18. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678396284Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-24 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678399484Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-21. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678402584Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-27 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678405584Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-24. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678408684Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-30 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678411784Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-27. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678417884Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-33 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678420984Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-30. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678423984Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-36 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678427184Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-33. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678430584Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-39 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678433684Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-36. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678436784Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-42 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678439884Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-39. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678442984Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-45 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678445984Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-42. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678449084Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Scheduling unloading of offsets and group metadata from __consumer_offsets-48 (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678452184Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-45. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
2019-04-11T12:32:24.678455283Z [2019-04-11 12:32:24,678] INFO [GroupMetadataManager brokerId=2] Finished unloading __consumer_offsets-48. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)`

**Comment by soylentseth** [comment]
Dumb question but you changed the resource values (memory) in the k8s manifest as well, right?  You would have seen the OOM messages in the pod description though.

**Comment by ammills01** [comment]
> Dumb question but you changed the resource values (memory) in the k8s manifest as well, right? You would have seen the OOM messages in the pod description though.

No question is a dumb one, right?  :)  The answer is no, but I'm literally sending 5 records per second to the cluster so I wasn't considering that 'Production' load.  Looking at the setting again, I see it's at 600mb and the pods are hovering around 598, so that's probably the issue.  I'll bump that and see if it corrects the issue.

**Comment by soylentseth** [comment]
heh i ran into kafka restarts without _any_ load seeing similar memory usage.  i had fewer restarts on ZK but none on either after  bumping kafka's limit to 1Gi.  The OOM messages were evident on a kubectl describe pod <kafka>

**Comment by ammills01** [comment]
Ok, I've been running for several hours now without a reboot at all.  I've added quite a bit more load to it and it's still truckin' right along.  Thanks for your help soylentseth!  I'll close this issue and hopefully someone will find it helpful in the future.
