### ISSUE TITLE
Problem starting Cruise Control

### ISSUE THREAD

**Issue by agallimore-gravity** [Yolean/kubernetes-kafka#287]
How much of the sample config needs to be changed? When the cruise-control pod starts it complains about the config entries like so

```
542    [           main] WARN  lients.consumer.ConsumerConfig  - The configuration 'sample.store.class' was supplied but isn't a known config.
542    [           main] WARN  lients.consumer.ConsumerConfig  - The configuration 'default.goals' was supplied but isn't a known config.
```

however 'default.goals' is a required entry. when commenting it out, it rightfully complains about a missing required entry. 

I'm not sure how to fix this

**Comment by solsson** [comment]
Based on https://github.com/Yolean/kubernetes-kafka/pull/218#issuecomment-448740529 it looks like those warnings have been there from the start. Also see https://github.com/Yolean/kubernetes-kafka/issues/250 about how it's sometimes non-obvious what Cruise Control's logs mean. Maybe your setup is working?

**Comment by agallimore-gravity** [comment]
it crashes right after

```
547    [           main] INFO  .apache.kafka.clients.Metadata  - Cluster ID: 5YMUrVGkTXe_Okw-X22Cbg
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at java.base/java.util.Properties.put(Properties.java:1316)
        at java.base/java.util.Properties.setProperty(Properties.java:225)
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.createConsumer(KafkaSampleStore.java:198)
        at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore.configure(KafkaSampleStore.java:157)
        at com.linkedin.kafka.cruisecontrol.config.KafkaCruiseControlConfig.getConfiguredInstance(KafkaCruiseControlConfig.java:1304)
        at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:104)
        at com.linkedin.kafka.cruisecontrol.monitor.task.LoadMonitorTaskRunner.<init>(LoadMonitorTaskRunner.java:74)
        at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:177)
        at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:127)
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:124)
        at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:75)
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:71)
```

should have included that first

**Comment by solsson** [comment]
Because Cruise Control 2 was at an early stage back in #218 I've kept bumping to new versions. Maybe something changed. I've triggered another build just now that should be ready in an hour or so. We could try that one, and after that troubleshoot.

**Comment by solsson** [comment]
e113521e1680d07c76a7c356733d8cf4e1581923 gets you the latest release.

I think the warnings are the result of one set of properties being used for multiple components.

**Comment by agallimore-gravity** [comment]
That worked, thanks!
