### ISSUE TITLE
Error processing /etc/kafka/zookeeper.properties.scale-5.pzoo-0

### ISSUE THREAD

**Issue by tan02** [Yolean/kubernetes-kafka#329]
[2020-08-19 03:28:39,910] INFO Reading configuration from: /etc/kafka/zookeeper.properties.scale-5.pzoo-0 (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2020-08-19 03:28:39,929] ERROR Invalid config, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain)
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /etc/kafka/zookeeper.properties.scale-5.pzoo-0
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:156)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:113)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
Caused by: java.lang.IllegalArgumentException: /etc/kafka/zookeeper.properties.scale-5.pzoo-0 file is missing
	at org.apache.zookeeper.server.util.VerifyingFileFactory.doFailForNonExistingPath(VerifyingFileFactory.java:51)
	at org.apache.zookeeper.server.util.VerifyingFileFactory.validate(VerifyingFileFactory.java:45)
	at org.apache.zookeeper.server.util.VerifyingFileFactory.create(VerifyingFileFactory.java:40)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:141)
	... 2 more
Invalid config, exiting abnormally

**Comment by solsson** [comment]
What commands did you use to apply, and from which git ref?

**Comment by tan02** [comment]
(1)kustomize build . | kubectl apply -f-  (2)https://github.com/Yolean/kubernetes-kafka/tree/master/zookeeper

**Comment by junan-732** [comment]
I have the same question,how to fix it? THS

**Comment by jaeyj2** [comment]
i have same exception. 
It seems that we need to modify the zookeeper.properties related part of configmap.
But I don't know which of the many lines is the problem. Because the log only came out missing files.

**Comment by tan02** [comment]
@junan-732 @jaeyj2 
Modify zookeeper / 10zookeeper- config.yml Medium
ln -s /etc/kafka/ zookeeper.properties /etc/kafka/ zookeeper.properties.scale -5.$POD_ NAME
