### ISSUE TITLE
FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)

### ISSUE THREAD

**Issue by darkprisco** [Yolean/kubernetes-kafka#42]
Hi guys,
 I am using the template but I have some problem during some specific condition:

On kubernetes if I restart the agent, once all are on my kafka pods are still crashing:

kubectl get pods --namespace kafka
NAME      READY     STATUS             RESTARTS   AGE
kafka-0   0/1       CrashLoopBackOff   12         2d
kafka-1   0/1       CrashLoopBackOff   11         2d
kafka-2   0/1       CrashLoopBackOff   9          2d
zoo-0     1/1       Running            1          2d
zoo-1     1/1       Running            1          2d
zoo-2     1/1       Running            2          2d
zoo-3     1/1       Running            1          2d
zoo-4     1/1       Running            2          2d

kubectl get nodes --namespace kafka
NAME                    STATUS                     AGE       VERSION
k8s-agent-fb4b805d-0    Ready                      4d        v1.6.6
k8s-agent-fb4b805d-1    Ready                      4d        v1.6.6
k8s-agent-fb4b805d-2    Ready                      4d        v1.6.6

Here the error:

org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:76)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:58)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:327)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:200)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2017-07-24 08:36:05,258] INFO shutting down (kafka.server.KafkaServer)
[2017-07-24 08:36:05,261] INFO shut down completed (kafka.server.KafkaServer)
[2017-07-24 08:36:05,262] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:76)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:58)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:327)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:200)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2017-07-24 08:36:05,263] INFO shutting down (kafka.server.KafkaServer)

What I can do?
Tks
Prisco

**Comment by solsson** [comment]
I'm a bit surprised that kafka uses the full service name `zookeeper.kafka.svc.cluster.local`, but that should work too. What do the zookeeper logs say? Any sign that they found each other and formed a cluster. You should see them logging the size of the cluster.

**Comment by darkprisco** [comment]
I am trying to reproduce the problem by perform the same steps I did but currently the address is not changing.. once I can reproduce the fault I will take all information/logs.. 

What about the deployment  of ZK on a dedicated cluster? 
Any consideration on this?

**Comment by darkprisco** [comment]
This is what I am looking after a restart:


> java.net.ConnectException: Connection refused (Connection refused)
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:381)
> 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:354)
> 	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
> 	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
> 	at java.lang.Thread.run(Thread.java:745)
> 2017-07-24 14:47:50,809 [myid:3] - INFO  [WorkerSender[myid=3]:QuorumPeer$QuorumServer@149] - Resolved hostname: zoo-1.zoo to address: zoo-1.zoo/10.244.2.10
> 2017-07-24 14:47:50,809 [myid:3] - INFO  [WorkerReceiver[myid=3]:FastLeaderElection@600] - Notification: 1 (message format version), 5 (n.leader), 0x100000022 (n.zxid), 0xa6 (n.round), LOOKING (n.state), 3 (n.sid), 0x1 (n.peerEpoch) LOOKING (my state)
> 2017-07-24 14:47:50,812 [myid:3] - INFO  [WorkerReceiver[myid=3]:FastLeaderElection@600] - Notification: 1 (message format version), 5 (n.leader), 0x100000022 (n.zxid), 0xa6 (n.round), LOOKING (n.state), 4 (n.sid), 0x1 (n.peerEpoch) LOOKING (my state)
> 2017-07-24 14:47:51,012 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:QuorumPeer@844] - FOLLOWING
> 2017-07-24 14:47:51,013 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:ZooKeeperServer@173] - Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /datalog/version-2 snapdir /data/version-2
> 2017-07-24 14:47:51,013 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Follower@61] - FOLLOWING - LEADER ELECTION TOOK - 213
> 2017-07-24 14:47:51,013 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:QuorumPeer$QuorumServer@149] - Resolved hostname: zoo-4.zoo to address: zoo-4.zoo/10.244.2.9
> 2017-07-24 14:47:51,014 [myid:3] - WARN  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Learner@236] - Unexpected exception, tries=0, connecting to zoo-4.zoo/10.244.2.9:2888
> java.net.ConnectException: Connection refused (Connection refused)
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at org.apache.zookeeper.server.quorum.Learner.connectToLeader(Learner.java:228)
> 	at org.apache.zookeeper.server.quorum.Follower.followLeader(Follower.java:69)
> 	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:846)
> 2017-07-24 14:47:52,015 [myid:3] - WARN  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Learner@236] - Unexpected exception, tries=1, connecting to zoo-4.zoo/10.244.2.9:2888
> java.net.ConnectException: Connection refused (Connection refused)
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at org.apache.zookeeper.server.quorum.Learner.connectToLeader(Learner.java:228)
>

**Comment by darkprisco** [comment]
By looking to all my zoo.cfg replicas, all appears like below: 

```

/workspace/arwa/arwa/scripts/kafka$ kubectl exec -it zoo-0 cat /conf/zoo.cfg --namespace kafka
clientPort=2181
dataDir=/data
dataLogDir=/datalog
tickTime=2000
initLimit=5
syncLimit=2
server.1=zoo-0.zoo:2888:3888:participant
server.2=zoo-1.zoo:2888:3888:participant
server.3=zoo-2.zoo:2888:3888:participant
server.4=zoo-3.zoo:2888:3888:participant
server.5=zoo-4.zoo:2888:3888:participant
```

**Comment by solsson** [comment]
Do you have the chance to test this with v2.0.0? See https://github.com/Yolean/kubernetes-kafka/issues/28#issuecomment-321167839.

**Comment by sunfeng90** [comment]
`Socket server failed to bind to localhost:9092: Address already in use.
	at kafka.network.Acceptor.openServerSocket(SocketServer.scala:404)
	at kafka.network.Acceptor.<init>(SocketServer.scala:308)
	at kafka.network.SocketServer.$anonfun$createAcceptorAndProcessors$1(SocketServer.scala:126)
	at kafka.network.SocketServer.$anonfun$createAcceptorAndProcessors$1$adapted(SocketServer.scala:122)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at kafka.network.SocketServer.createAcceptorAndProcessors(SocketServer.scala:122)
	at kafka.network.SocketServer.startup(SocketServer.scala:84)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:247)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:92)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at kafka.network.Acceptor.openServerSocket(SocketServer.scala:400)
	... 12 more
[2018-05-05 10:47:59,923] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2018-05-05 10:47:59,928] INFO [SocketServer brokerId=0] Stopping socket server request processors (kafka.network.SocketServer)
[2018-05-05 10:47:59,937] INFO [SocketServer brokerId=0] Stopped socket server request processors (kafka.network.SocketServer)
[2018-05-05 10:47:59,944] INFO Shutting down. (kafka.log.LogManager)
[2018-05-05 10:48:00,003] INFO Shutdown complete. (kafka.log.LogManager)`

I got these errors. I try to kill the 9092 instance, but doesn't work for me!

**Comment by solsson** [comment]
Very odd. Is there multiple kafka processes in a single container, or multiple containers with a kafka process in the same pod?

**Comment by sunfeng90** [comment]
Maybe!

**Comment by saiwebaditya** [comment]
any luck on this?

**Comment by tl163** [comment]
have any update? I also meet the same issue.

**Comment by mdivk** [comment]
If you have fixed the issue, kindly share it with people who helped you here, this will also benefit people who had the same issue later. Thank you.
